describe('Basic Form test', () => {
    it('Asserts that text can be added to name box',() => {
        cy.visit('pizza/')
        cy.get('[name=name]')
            .type('testing')
            .should('have.value','testing')
    })
    it('Asserts that multiple toppings can be added',() => {
        cy.visit('pizza/')
        cy.get('[name=topping1')
            .click()
            .should('have.checked',true)
        cy.get('[name=topping2')
            .click()
            .should('have.checked',true)
    })
    it('Asserts that submit is functional',() => {
        cy.visit('pizza/')
        cy.get('#Submit')
            .should('be.disabled')
        cy.get('[name=size]')
            .select('Small')
        cy.get('#Submit')
            .should('be.disabled')
        cy.get('[name=name]')
            .type('testing')
        cy.get('#Submit')
            .should('not.be.disabled')
    })
})