describe('Pizza Order App', () => {

    beforeEach(() => {
        cy.request('fakeapi.com')
    })

    const sizeInput = () => cy.get('select[name="size"]')
    const saucesInput = () => cy.get('radio[name="sauces"]')
    const pepperoniInput = () => cy.get('checkbox[name="pepperoni"]')
    const italianSausageInput = () => cy.get('checkbox[name="italianSausage"]')
    const canadianBaconInput = () => cy.get('checkbox[name="canadianBacon"]')
    const chickenInput = () => cy.get('checkbox[name="chicken"]')
    const hamburgerInput = () => cy.get('checkbox[name="hamburger"]')
    const spicyItalianSausageInput = () => cy.get('checkbox[name="spicyItalianSausage"]')
    const pineappleInput = () => cy.get('checkbox[name="pineapple"]')
    const blackOlivesInput = () => cy.get('checkbox[name="blackOlives"]')
    const jalepenoPeppersInput = () => cy.get('checkbox[name="jalepenoPeppers"]')
    const onionsInput = () => cy.get('checkbox[name="onions"]')
    const greenPeppersInput = () => cy.get('checkbox[name="greenPeppers"]')
    const mushroomsInput = () => cy.get('checkbox[name="mushrooms"]')
    const specialInstructionsInput = () => cy.get('input[name="specialInstructions"]')
    const submitButton = () => cy.get('button[id="button"]')

    it('can select multiple toppings', ()=> {
        pepperoniInput()
            .should('have.value', true)
        italianSausageInput()
            .should('have.value', true)
        canadianBaconInput()
            .should('have.value', true)
        canadianBaconInput()
            .should('have.value', true)
        chickenInput()
            .should('have.value', true)
        hamburgerInput()
            .should('have.value', true)
        spicyItalianSausageInput()
            .should('have.value', true)
        pineappleInput()
            .should('have.value', true)
        blackOlivesInput()
            .should('have.value', true)
        jalepenoPeppersInput()
            .should('have.value', true)
        onionsInput()
            .should('have.value', true)
        greenPeppersInput()
            .should('have.value', true)
        mushroomsInput()
            .should('have.value', true)

    })

    it('should add text to the box', () => {
        specialInstructionsInput()
            .should('have.value', '')
            .type('put pizza on porch and ring bell')
            .should('have.value', 'put pizza on porch and ring bell' )
    })

    it('should submit the form', () => {
        sizeInput().select('small')
        saucesInput.radio('marinara')
        submitButton().should('not.be.disabled')
    })
})
